<?php
$currencys = array(
	"USD" => '$',
	"AUD" => '$',
	"EUR" => '€',
	"BRL" => 'R$',
	"CAD" => '$',
	"CZK" => 'Kč',
	"DKK" => 'kr',
	"HKD" => '$',
	"HUF" => 'Ft',
	"INR" => '₹',
	"ILS" => '₪',
	"JPY" => '¥',
	"MYR" => 'RM',
	"MXN" => '$',
	"TWD" => 'NT$',
	"NZD" => '$',
	"NOK" => 'kr',
	"PHP" => '₱',
	"PLN" => 'zł',
	"GBP" => '£',
	"RUB" => 'руб',
	"SGD" => '$',
	"CHF" => 'CHF',
	"THB" => '฿',
	"TRY" => '₺',
	"ZAR" => 'R',
	"NGN" => '₦',
	"VND" => 'đ',
	"BDT" => '৳'
);


$LANG = array(
	/*WELLCOME*/
	'welcome_to' => 'Welcome to ' . $siteName . '!',
	'signup_for' => 'Sign up to <span>make money</span> and discover <span>exlusively</span> the contents of your favouret stars!',
	'menu' => 'Menu',
	'login' => 'Login',
	'sign_up' => 'Sign Up',
	'moniteize_your_content' => 'Remember that you can monetize your content.',
	'try_site_for_free' => 'Try ' . $siteName . ' for free',
	/*FOOTER PAGE MENU*/
	'about-us' => 'About Us',
	'privacy-policies' => 'Privacy Policies',
	'contact' => 'Contact',
	'terms-of-use' => 'Terms Of Use',
	'cookies' => 'Cookies',
	'terms-of-sales' => 'Terms of sales',
	/*404 PAGE*/
	'page-not-found' => 'Page Not Found',
	'sorry-this-page-not-available' => 'Sorry, this page isn\'t available.',
	'link-not-found' => "The link you followed may be broken, or the page may have been removed. Go back to <a href='$base_url'>Home Page</a>.",
	/*HEADER*/
	'look-at-your-profile' => 'Look at your profile',
	'dashboard' => 'Dashboard',
	'payments' => 'Payments',
	'subscribers' => 'Subscribers',
	'subscriptions' => 'Subscriptions',
	'settings' => 'Settings',
	'day-night' => 'Day / Night Mode',
	'logout' => 'Logout',
	'saved' => 'Saved',
	'languages' => 'Languages',
	/*HEADER MESSAGE NOTIFICATIONS*/
	'see_all_in_messenger' => 'See all in messenger',
	'messages' => 'Messages',
	'notifications' => 'Notifications',
	'see_all_messages' => 'See All Messages',
	'delete_message' => 'Delete Message',
	'mark_as_read' => 'Mark as read', /*This word will be appear on notifications also*/
	'see_all_notifications' => 'See all notifications',
	/*HEADER NOTIFICATIONS*/
	'remove_this_notification' => 'Remove This Notification',
	/*LOGIN POPUP*/
	'you-are-back' => 'You Are Back!',
	'login-to-access-your-account' => 'Login to access your account',
	'login-with' => 'Login With',
	'twitter' => 'Twitter',
	'google' => 'Google',
	'or-directly' => 'or directly',
	'username-or-email' => 'Username or Email address',
	'username-or-email-ex' => 'e.g: john or john@hotmail.com',
	'password' => 'Password',
	'login' => 'Login',
	'not-member-yet' => 'Not a member yet?  <a href="' . $base_url . 'register">Sign up now!</a>',
	'forgot-password' => 'Forgot your password?',
	'change-password' => 'Change Password!',
	'never-mind' => 'Never mind! It happens to everyone...',
	'send' => 'Send',
	'already-member' => 'Already a Member?',
	'email-address' => 'Email Address',
	'your_email_address' => 'Your Email Address',
	/*REGISTER*/
	'you_are' => 'You are',
	'your_full_name' => 'Your full name',
	'your_username' => 'Your username',
	'accept_terms_of_conditions_register' => 'By clicking Register, you agree to our <a href="' . $base_url . 'terms-of-use">Terms of Use</a> and <a href="' . $base_url . 'cookies">Cookie Policy</a>.',
	'full_for_register' => 'Please fill in all the information completely.',
	'passwor_too_short' => 'Your password must be at least 6 characters. It should not contain spaces.',
	'username_should_not_be_empty' => 'The username should not be empty.',
	'try_different_username' => 'This username is used by someone else. Please try to create a different username.',
	'short_username' => 'Username must be at least 6 characters.',
	'invalid_username' => 'Your username contains invalid characters.',
	/*LEFT MENU*/
	'profile' => 'Profile',
	'home_page' => 'Home Page',
	'newsfeed' => 'Newsfeed',
	'explore' => 'Explore',
	'premium' => 'Premium',
	'our_creators' => 'Our Creators',
	/*No More Messages*/
	'no_more_notifications' => 'No more notification will be shown.',
	'no_post_will_be_shown' => 'There is nothing to show for the moment. Start by posting something or follow members to make sure you don’t miss any posts!',
	'no_post_wilbe_shown_in_this_profile' => 'No more post will be shown on this profile!',
	/*Who Can See List*/
	'whocanseethis' => 'Who can see this?',
	'weveryone' => 'Everyone',
	'wfollowers' => 'Followers',
	'wsubscribers' => 'Subscribers',
	'wpremium' => 'Premium',
	'select_privacy' => 'Select Privacy',
	/*Post Menu*/
	'edit_post' => 'Edit Post',
	'edit_comment' => 'Edit Comment',
	'pin_on_my_profile' => 'Pin on my profile',
	'copy_post_url' => 'Copy Post URL',
	'disable_comment' => 'Disable comment',
	'delete_post' => 'Delete Post',
	'report_this_post' => 'Report this post',
	'unreport' => 'Unreport',
	'reported' => 'Post Reported',
	'delete_comment' => 'Delete Comment',
	'comment_delete_alert_not' => 'Are you sure you want to delete this comment?',
	'report_comment' => 'Report Comment',
	'comments_disabled' => 'Comments Disabled!',
	'comments_opened' => 'Comments Enabled!',
	'enable_comments' => 'Enable Comment',
	'comments_disabled_success' => 'Comments have been disabled. Only you can comment on this post.',
	'comments_enabled_success' => 'Comments are activated. Now other people, including you, will be able to comment on the post.',
	/*SHARE ON BUTTON*/
	'share_on_facebook' => 'Share on Facebook',
	'share_on_twitter' => 'Share on Twitter',
	/*File UPLOAD*/
	'image_video' => 'Image/Video',
	/*Post Form*/
	'publish' => 'Publish',
	'write_message_add_photo_or_video' => 'Write your message, add your photo or Video ...',
	/*Subscriber*/
	/*
		    {userPostOwnerUserFullName} this is main text don't change it
	*/
	'only_subscribers' => '<p><strong>Subscribers</strong></p><p>If you want to see the contents of <strong>{userPostOwnerUserFullName}</strong> reserved for fans.</p>',
	'only_followers' => '<p><strong>Followers</strong></p><p>If you want to see the contents of <strong>{userPostOwnerUserFullName}</strong> reserved for followers.</p>',
	'must_login_for_comment' => 'You must be logged in to write a comment.',
	'comments_limited_for_this_post' => 'Comments have been limited for this post.',
	'write_your_comment' => 'Write your comment...',
	're_share_title' => 'Re Share',
	/* added by nazar */
	'post_details' => 'Post Details',
	/* end */
	'share' => 'Share',
	'empty_shared_title' => 'This content isn\'t available at the moment',
	'empty_shared_desc' => 'When this happens, it\'s usually because the owner only shared it with a small group of people or changed who can see it, or it\'s been deleted.',
	'can_not_share_title' => 'Could not be shared!',
	'can_not_share_desc' => 'Because this post is no longer available.',
	'please_enter_a_message_or_add_a_photo_or_video' => 'Please enter a message or add a photo or video',
	'file_not_found' => 'File not found!',
	'file_not_found_not' => 'An error occurred, please try again later.',
	'noway' => 'No way!',
	'noway_desc' => 'Something went wrong, please try again later!',
	'write_something_about_the_post' => 'Write something about the post!',
	'save_edit' => 'Save',
	'can_not_save_blank_post' => 'You left the post you are editing blank.',
	'delete_post_alert_note' => 'This action is irreversible. Are you sure you want to continue?',
	'ok' => 'Ok',
	'no' => 'No',
	'cancel' => 'Cancel',
	'accept' => 'Accept',
	'post_deleted' => 'Post Deleted!',
	'comment_deleted' => 'Comment Deleted!',
	'delete_success' => 'Post Deleted Successfully',
	'delete_comment_success' => 'Comment Deleted Successfully',
	'post_could_not_be_delete' => 'There was a problem processing your request, please try again later.',
	'suggest_post_title' => 'More Posts from {userPostOwnerUserFullName}',
	'copied' => 'Copied!',
	'link_copied' => 'Link copied successfully',
	/*Post Pin*/
	'post_pined_on_your_profile' => 'Pined on your profile',
	'post_pined_on_your_profile_notification_desc' => 'This post is pined on your profile. People who visited your profile will now view this post at the top.',
	'pinClosed' => 'Pin Removed!',
	'pinClosed_notification_desc' => 'The post is no longer pinned in your profile.',
	'added_in_saved_list' => 'Added in Saved List',
	'post_in_your_saved_list' => 'It has been added to your saved list.',
	'removed_in_saved_list' => 'Removed in Saved List',
	'post_removed_in_saved_list' => 'It has been removed to your saved list.',
	'smileys' => 'Smileys',
	'gestures_and_bodyparts' => 'Gestures and Body Parts',
	'people_and_fantasy' => 'People & Fantasy',
	'clothing_and_accessories' => 'Clothing and Accessories',
	'pale_emojis' => 'Pale Emojis',
	'cream_white_emojis' => 'Cream White Emojis',
	'brown_emoji' => 'Brown Emojis',
	'dark_brown_emoji' => 'Dark Brown Emojis',
	'black_emoji' => 'Black Emojis',
	'anmal_nature' => 'Animal & Nature',
	'food_and_drink' => 'Food & Drinks',
	'activity_and_sports' => 'Activity & Sports',
	'travel_and_places' => 'Travel & Places',
	'objects' => 'Objects',
	'symbols' => 'Symbols',
	'non_emoji_symbols' => 'Non Emoji Symbols',
	'flags' => 'Flags',
	'could_not_fined_gif' => 'Could not fined gif',
	'online_now' => 'Online Now',
	'joined' => 'Joined',
	'become_a_subscriber' => 'Become a Subscriber',
	'unsubscribe' => 'UnSubscribe',
	'follow' => 'Follow',
	'unfollow' => 'UnFollow',
	'subscription_benefits' => 'SUBSCRIPTION BENEFITS:',
	'full_acces_to_conent' => 'Full access to this user\'s content',
	'direct_message_this_user' => 'Direct message with this user',
	'cancel_follow_any_time' => 'Cancel your follow at any time',
	'cancel_subs_any_time' => 'Cancel your subscription at any time',
	'follow_for_free' => 'FOLLOW FOR FREE',
	'you_are_following' => 'You are now following this user. You can see the posts of this user in your news feed.',
	'you_are_unfollowing' => 'You removed the user from your following list. You will no longer be able to see any posts from this user in the news feed.',
	'subscribeNot' => 'Support {f_userfullname} and get unlimited access to very special fan-only content!',
	'are_you_sure_want_to_block' => 'Are you sure you want to block {f_userfullname} ?',
	'no_longer_be_able_to' => '{f_userfullname} will no longer be able to:',
	'also_you_no_longer_be_able_to' => 'Also you will no longer be able to:',
	'tag_you' => 'Tag you',
	'message_you' => 'Message you',
	'comment_on_your_post' => 'Comment on your post',
	'tag_you_you' => 'Tag {f_userfullname}',
	'message_you_you' => 'Message {f_userfullname}',
	'comment_on_his_post' => 'Comment on {f_userfullname}\'s post',
	'restrict' => 'Restrict {f_userfullname}',
	'block_completely' => 'Block {f_userfullname} completely',
	'see_your_post_on_your_timeline' => 'See your posts on your timeline',
	'can_not_follow_you' => 'Follow your profile',
	'can_not_subscribe_you' => 'Subscribe your profile',
	'block_unfollow_not' => 'If {f_userfullname} follow your profile, blocking {f_userfullname} will also unfullow.',
	'block_unsubscribe_not' => 'If {f_userfullname} subscribe you, blocking {f_userfullname} will also unsubscribe.',
	'note_blocker' => 'If you are following {f_userfullname} or if you are a subscriber, both your subscription and your follow will be canceled.',
	'avantages_of_subscription' => 'AVANTAGES OF SUBSCRIPTION',
	'unblock_all_fan_contents' => 'Unblock all my <strong> funs contents</strong>',
	'full_acces_my_conent' => 'Full access to my content',
	'direct_message_me' => 'Direck message me',
	'offers' => 'OFFERS',
	'subscribe_for' => 'Susbscribe for <span>{planAmount}',
	'weekly' => 'Weekly',
	'monthly' => 'Monthly',
	'yearly' => 'Yearly',
	'subscription_payment' => 'You are currently subscribing to the person named <strong>{f_userfullname}<strong>',
	'subscription_renew' => 'For your convenience, your subscription will be automatically renewed. You can cancel your subscription at any time.',
	'card_holder' => 'CARD HOLDER',
	'email' => 'Email',
	'card_number' => 'CARD NUMBER',
	'expiration_date' => 'EXPIRATION DATE',
	'expiration_month' => 'EXPIRATION MONTH',
	'expiration_year' => 'EXPIRATION YEAR',
	'ccv_code' => 'CVC CODE',
	'pay' => 'PAY',
	'subscription_activation_failed' => 'Subscription activation failed!',
	'subscription_creation_failed' => 'Subscription creation failed!',
	'plan_creation_failed' => 'Plan creation failed!',
	'invalid_card_details' => 'Invalid card details!',
	'contact_site_administrator' => 'Something went wrong, please contact the site administration!',
	'become_creator' => 'Become a Creator',
	'registeration_free_fast' => 'Registration is free and very fast!',
	'certification' => 'Certification',
	'validation' => 'Validation',
	'conditions' => 'Conditions',
	'fees' => 'Fees',
	'payouts' => 'Payout',
	'account_certification' => 'Account certification',
	'please_provide_follows_for_certify_your_account' => 'To verify your identity and certify your account, please provide us with:',
	'scan_photo_of_your_id_card' => 'A scan or photo of your ID card.',
	'photo_of_you_holding_id_vard_and_sign' => 'A photo of you holding the ID card and a sign saying: <strong>« ' . $siteName . ' », your username and the date of the day.</strong>',
	'upload_id_card' => 'Upload ID Card',
	'max_size' => 'Maxsize ' . $availableUploadFileSize . 'Mb',
	'accept_terms_of_conditions' => 'By clicking the Next button, you accept the <a href="' . $base_url . 'terms-of-sales">general terms and conditions of use</a> of ' . $siteName . '.',
	'next' => 'Next',
	'readed_conditions' => 'Here are some important points about your account. Please read to continue. And after reading, press the next button.',
	'setup_subscribers_fee' => 'Setup Subscribers Fee',
	'setup_subscribers_fee_note' => 'Set fees for people who want to subscribe to your profile. Pricing can be made in <strong>3 different ways: Weekly, Monthly, Yearly</strong>. <p>These charges will be renewed automatically when they expire.<p> <li>If you block your subscribers or if they block you, subscriptions will be automatically canceled.</li> <li>You can activate or deactivate your subscription pricing. After the fees you earn while active, become passive, your subscriptions continue until your member cancels.</li><li>Changing the fee will not change the price of previous subscribers.</li>',
	'weekly_subs_fee' => 'Weekly subscription fee',
	'weekly_subs_fee_not' => 'Payments are made weekly by the subscriber.',
	'weekly_subs_ex_fee' => '3',
	'monthly_subs_fee' => 'Monthly subscription fee',
	'monthly_subs_fee_not' => 'Payments are made monthly by the subscriber.',
	'monthly_subs_ex_fee' => '25',
	'yearly_subs_fee' => 'Yearly subscription fee',
	'yearly_subs_fee_not' => 'Payments are made yearly by the subscriber.',
	'yearly_subs_ex_fee' => '249',
	'minimum_yearly_subscription_fee' => 'Annual subscription fee should be a minimum of ' . $currencys[$defaultCurrency] . $subscribeYearlyMinimumAmount . '',
	'minimum_monthly_subscription_fee' => 'The monthly subscription fee should be a minimum of ' . $currencys[$defaultCurrency] . $subscribeMonthlyMinimumAmount . '',
	'minimum_weekly_subscription_fee' => 'The weekly subscription fee should be a minimum of ' . $currencys[$defaultCurrency] . $subscribeWeeklyMinimumAmount . '',
	'must_specify_weekly_subscription_fee' => 'You have activated the weekly subscription fee, but haven\'t requested a fee. Please specify the weekly subscription fee.',
	'must_specify_monthly_subscription_fee' => 'You have activated the monthly subscription fee, but haven\'t requested a fee. Please specify the monthly subscription fee.',
	'must_specify_yearly_subscription_fee' => 'You have activated the yearly subscription fee, but haven\'t requested a fee. Please specify the yearly subscription fee.',
	'payout_methods' => 'Payout Methods',
	'payout_method' => 'Payout Method',
	'payout_methods_not' => 'There are two different payment types available to you below. You can use only one of these two payment options as default. However, you can change the default payment type at any time. Your payments are transferred to your default account.',
	'paypal' => 'PayPal',
	'defaultPayout' => 'Default',
	'bank_transfer' => 'Bank Transfer',
	'bank' => 'Bank',
	'paypal_payout_warning' => 'You have assigned PayPal as the default payment account, but did not fill in the required fields. Please write your paypal information that you chose as default payment area.',
	'paypal_email_address_not_match' => 'The payment e-mail addresses you specified for paypal do not match.',
	'if_default_not' => 'Check the box on the right if you want paypal to be the default payment option.',
	'paypal_email' => 'PayPal Email',
	'confirm_paypal_email' => 'Confirm PayPal Email',
	'if_default_not_bank' => 'Check the box on the right if you want bank to be the default payment option.',
	'bank_payout_warning' => 'You have assigned Bank Transfer as the default payment account, but did not fill in the required fields. Please write your Bank Details: Swift Code, Account Number, Branch Name, IBAN...',
	'bank_transfer_placeholder' => 'Bank Details: Swift Code, Account Number, Branch Name, IBAN...',
	'invalid_email_address' => 'Invalid Email Address',
	'conguratulation' => 'Congratulations',
	'conguratulation_note' => 'Congratulations. You are now a creator. Your monetization settings have been activated. You can use from the <a href="' . $base_url . 'settings">Dashboard</a> page to edit your settings.',
	/*Settings Page*/
	'menu_arrow_account_title' => 'ACCOUNT',
	'my_profile' => 'My Profile',
	'profile_pictures' => 'Profile pictures',
	'modify_avatar_cover' => 'Modify avatar and/or cover image',
	'email_address' => 'Email Address',
	'full_name' => 'Full Name',
	'username' => 'Username',
	'your_profile_url' => 'Your Profile URL:',
	'you_are_a' => 'You are',
	'male' => 'Male',
	'female' => 'Female',
	'couple' => 'Couple',
	'birthday' => 'Birthday',
	'birthday_help' => 'Date in the format DD/MM/YYYY (for example 31/01/1989)',
	'birthday_format_placeholder' => 'DD/MM/YYYY',
	'description' => 'Description',
	'description_placeholder' => 'Description yourself in a few words',
	'category' => 'Category',
	'personalizeyourprofile' => 'Personalize your profile!',
	'helps_to_gain_visibility' => 'Adding an avatar and a cover image greatly helps to gain visibility!',
	'cover_image_modification' => 'Cover Image modification',
	'profile_image_modification' => 'Profile Image modification',
	'finished' => 'Finished',
	'username_already_in_use_warning' => 'You can not use this username because it is already in use',
	'username_special_character_warning' => 'Username should not contain any special characters, symbols or spaces.',
	'username_least_character_warning' => 'Your username must be at least 5 characters.',
	'changing_email_address' => 'Changing your email address',
	'changing_email_adress_not' => 'You will need to recheck your address if you change it',
	'your_new_email_address' => 'Your new email address',
	'your_current_password' => 'Your current password',
	'email_already_in_use_warning' => 'This e-mail address is in use by another person.',
	'wrong_password' => 'Wrong password!',
	'warning_same_email' => 'You are already using this email address!',
	'this_field_is_required' => 'This field is required.',
	'email_changed_success' => 'Your e-mail address has been successfully changed.',
	'profile_updated_success' => 'Profile settings are updated successfully!',
	'history_of_all_subscriptions_received' => 'History of all subscriptions payments received',
	'history_of_all_payments_received' => 'History of all payments received',
	'history_of_all_payments_you_made' => 'History of all payments you made',
	'active' => 'Active',
	'inactive' => 'Cancelled',
	'subscriber' => 'Subscriber',
	'started_at' => 'Started at',
	'amount' => 'Amount',
	'earning' => 'Earning',
	'status' => 'Status',
	'id' => 'ID',
	'next_page' => 'Next',
	'preview_page' => 'Prev',
	'payment_settings_updated_success' => 'Your payment settings have been updated successfully.',
	'subscription' => 'Subscription',
	'payout_history' => 'Payout History',
	'history_of_all_payouts_received' => 'List of all received and pending payments',
	'date' => 'Date',
	'invoice' => 'Invoice',
	'pending' => 'Pending',
	'success' => 'Success',
	'declined' => 'Declined',
	'withdrawal' => 'Withdrawal',
	'send_withdrawal_not' => 'Through this page, you can send a money transfer request to your account.',
	'minimmum_withdrawal_amount' => 'Minimum withdrawal amount is ' . $currencys[$defaultCurrency] . $minimumWithdrawalAmount . '. (*)Your payment would be available in 7 business day(s). (*)You can request payment only once at a time.',
	'not_default_payment_method' => 'Your default payment method is ' . $payoutMethod . ' you can change it by clicking on <a href="' . $base_url . 'settings?tab=payout_methods">this page</a>.',
	'calculated_monthly_payout' => 'Currently your monthly subscription earnings are <strong>' . $currencys[$defaultCurrency] . $cEarning . '</strong> for next month\'s payment. Payouts are processed on the 15th of each month. To be eligible for a payout on the 15th you must have been eligible by the last day of the previous month.',
	'your_available_balance' => 'Balance: ' . $currencys[$defaultCurrency] . $userWallet . '',
	'balance' => 'Balance',
	'request_withdrawal' => 'Request withdrawal',
	'minimum_withdrawal_amount' => 'Minimum withdrawal amount is ' . $currencys[$defaultCurrency] . $minimumWithdrawalAmount . '',
	'type' => 'Type',
	'budget_not_enough' => 'Your budget is not enough to withdraw.',
	'withdrawal_success' => 'Your payment request has been successfully received, you can find out your payment request status by clicking <a href="' . $base_url . 'settings?tab=payout_history">HERE</a>.',
	'wait_for_pending' => 'You currently have an existing pending payment. Please wait until your current payment has been made. Click <a href="' . $base_url . 'settings?tab=payout_history">HERE</a> to view your pending withdrawal request.',
	'premium_zone' => 'PREMIUM ZONE',
	'subscription_payments' => 'Subscription Payments',
	'waiting_for_approve' => 'Waiting for approve!',
	'free_for_subscribers' => 'Free for subscribers!',
	'points' => 'Points',
	'post_credit' => '<span>{userPostWantedCredit}</span> points',
	'purchase_post' => 'Purchase this post!',
	'purchase' => 'Purchase',
	'purchasing' => 'Purchasing',
	'confirm' => 'Confirm',
	'pr_photo' => '{totalPhotos} photo',
	'pr_video' => '{totalVideos} video',
	'supply_of_wallet' => 'Supply of your wallet',
	'purchase_of_points' => 'Purchase of points',
	'discovery' => 'Discovery',
	'naughy' => 'Naughy',
	'amateur' => 'Amateur',
	'confirmed' => 'Confirmed',
	'expert' => 'Expert',
	'royal' => 'Royal',
	'for' => 'for',
	'choose_payment_method' => 'Choose Payment Method',
	'point_buy_not' => 'You are currently buying {planPoint} points worth ' . $currencys[$defaultCurrency] . '{planAmount} . Please fill in the information below and click the pay button.',
	'payment_failed_desc' => 'It looks like you canceled the payment or have a problem with your card. Please try again.',
	'payment_failed_title' => 'Oh, no! Payment filed!',
	'back_home_page' => 'Go Back to Home page',
	'go_profile_page' => 'Go to your Profile',
	'you_can_use_instantly' => 'You can use your points instantly after payment.',
	'next_payout' => 'Next payout',
	'paid_by' => 'Paid by',
	'list_subscribers_not' => 'List of people who have subscribed to your profile.',
	'list_subscribed_not' => 'List of people whose profile you have subscribed to',
	'you_bought_points' => 'You bought {planPoint} points.',
	'privacy' => 'Privacy',
	'preferences' => 'Preferences',
	'blocked' => 'Blocked',
	'block_page_not' => 'You can view and unblock people you have blocked on this page.',
	/*Email Words*/
	'bought_point_success' => 'The point purchase is successful.',
	'thank_you_for_purchase_not' => 'You bought {planPoint} points worth ${planMoney}. You can use your points to view premium posts. We thank you.',
	'start_using_your_points' => 'Start using your points',
	'not_qualify_document' => 'This email does not qualify as a document.',
	'commented_on_your_post' => 'Someone commented on your post.',
	'commented_below' => 'Commented below',
	'liked_your_post' => 'Liked your post',
	'someone_liked_yourpost' => 'Someone liked your post',
	'click_go_post' => 'Click here to go post',
	'liked_your_comment' => 'Liked your Comment',
	'someone_liked_your_comment' => 'Someone liked your comment',
	'click_go_comment' => 'Click here to see comment',
	'someone_bought_your_post' => 'Someone bought your post.',
	'you_earn_money' => 'Congratulations, you earn money.',
	'now_following_your_profile' => 'Started to following your profile',
	'fill_all_credit_card_details' => 'In order to start your subscription, your card information must be entered below. Please check your card details',
	'got_new_subscriber' => 'You got new subscriber',
	'share_something_for_subscriber' => 'Don\'t forget to share something for them in order to gain more subscribers and make your existing subscribers permanent.',
	'write_points' => 'Write points',
	'point_wanted' => 'How many points do you want for this post to be seen? One point: $' . $onePointEqual . '',
	'must_write_point_for_post' => 'Currently you are about to share premium post. So must specify a point fee for your post.',
	'must_upload_files_for_premium' => 'To create a premium post, you must upload files.',
	/*CHAT*/
	'chat' => 'Chat',
	'no_more_message' => 'There are no more messages to show.',
	'typing' => 'Typing...',
	'last_seen' => 'Last seen ',
	'online' => 'Online',
	'isSticker' => 'Sticker',
	'isImage' => 'Image',
	'isGif' => 'Gif',
	'commented_on_your_post' => 'Commented on your post',
	'liked_your_post' => 'Liked your post',
	'liked_your_comment' => 'Liked your comment',
	'is_now_following_your_profile' => 'is now following your profile',
	'is_subscribed_your_profile' => 'is now subscribing your profile',
	'accepted_post' => 'your post has been approved for publication',
	'rejected_post' => 'your post rejected',
	'declined_post' => 'your post declined',
	'best_creators_last_week' => 'Top 5 creators of last week!',
	'super_active' => 'Super Active',
	'very_active' => 'Very Active',
	'active_' => 'Active',
	'best_creators_of_last_week' => 'The best creators of last week',
	'no_posts_yet' => 'No posts yet',
	'not_creator_in_this_caregory' => 'Oh no! At the moment there are no creators in this category',
	'no_more_creator_will_be_shown' => 'No more creator will be shown in this category!',
	'can_fined_some_data' => 'Here you can find some data on your earnings.',
	'subscription_earnings' => 'Subscription Earnings',
	'point_earnings' => 'Premium Content Earning',
	'current_month_earning' => 'Earnings for this month (' . date('M') . ')',
	'premium_question_hover_display' => 'It is the total earnings you earn from premium posts',
	'subscribe_question_hover_display' => 'It is the earnings you will receive each month from people who subscribe to your profile. This earning can vary, if one or more of your subscribers unsubscribe from your profile, this earning may decrease.',
	'view_more' => 'View More',
	'make_withdrawal' => 'Make withdrawal',
	'no_one_you_subscribed' => 'There\'s no one you subscribed yet',
	'no_one_has_subscribed_to_your_profile' => 'No one has subscribed to your profile yet.',
	'saved_items' => 'Saved items',
	'total_plike' => '{likeSum} people like this',
	't_comments' => '{SecondUniqComment} Comments',
	'your_points' => 'Your Points',
	'purchase_point' => 'Purchase Point',
	'choose_language' => 'Choose language',
	'search_creators' => 'Search Creators',
	'search' => 'Search',
	'send_message' => 'Send Message',
	'shart_a_chat_with' => 'Start a chat with {f_userfullname}',
	'please_upload_all' => 'Please upload all necessary information',
	'please_upload_id_card' => 'Please upload ID card',
	'please_upload_id_photo' => 'Please upload ID Photo',
	'your_request_is_pending' => 'Your request is pending validation',
	'you_will_notififed_when_it_is_processed' => 'You will be notified when it is processed.',
	'rejected' => 'Your request for a refund has been rejected',
	'one_or_more_your_files_are_non_compliant' => 'One or more of your files are non-compliant.',
	'request_rejected_notification' => 'Your request to become Creator has been rejected.',
	'message_from_moderator' => 'Message from the moderator',
	'photo_unverified' => 'It was rejected for photos.',
	'unblock' => 'You blocked the contact {conversationUserFullName}. Unblock the person to continue the conversation. <a href="' . $base_url . 'settings?tab=blockList">UNBLOCK</a>',
	'unblock_me' => '{conversationUserFullName} was blocked you.',
	'delete_conversation' => 'Delete Conversation',
	'are_you_sure_to_delete_conversation' => 'Are you sure delete this conversaion?',
	'delete_message' => 'Delete Message',
	'are_you_sure_to_delete_message' => 'Are you sure delete this message?',
	'un_block' => 'UnBlock',
	'perfect_no_blocked_yet' => 'Perfect, you haven\'t blocked anyone.',
	'password_page_not' => 'When you have changed your password, you will be logged out of "<strong>' . $siteName . '</strong>" on all your devices.',
	'cur_password' => 'Current Password',
	'nw_password' => 'New Password',
	'confrm_new_password' => 'Confirm New Password',
	'warning_current_password_not_correct' => 'Please enter your existing password correctly.',
	'please_write_crnt_pass' => 'Please write your current password',
	'new_pass_not_match' => 'New passwords do not match',
	'no_new_password_wrote' => 'You did not enter your new password',
	'minimum_character_not' => 'Your password can consist of a minimum of 6 characters.',
	'not_contain_whitespace' => 'Your password should not contain any white spaces',
	'just_loged_in_user' => 'This person only shows their posts to people who are logged in.',
	/*PREFERENCES*/
	'email_notification_settings' => 'Email notification settings',
	'allow_email_notifications' => 'Allow email notification',
	'allow_email_notification_not' => 'You will be informed of your account activity by email in addition to the notifications on the site.',
	'message_notification_settings' => 'Message notification settings',
	'allow_message' => 'Allow people to send you messages',
	'allow_message_not' => 'When it\'s active, anyone can send you a message.',
	'profile_display_settings' => 'Profile display settings',
	'profile_display_settings_not' => 'Should people who are not members or not logged in, be able to see your posts?',
	'profile_display_settings_not_two' => 'When it is active, people who are not logged in can view your posts.',
	/*ADMIN PANEL*/
	'admin_dashboard' => 'Dashboard',
	'admin_panel' => 'Admin Panel',
	'general' => 'General',
	'limits' => 'Limits',
	'email_settings' => 'Email Settings',
	'storage' => 'Storage',
	'manage_posts' => 'Manage Posts',
	'posts' => 'Posts',
	'premium_posts' => 'Premium Pots',
	'for_subscribers' => 'Subscriber Posts',
	'awaiting_approval_posts' => 'Awaiting approval',
	'view_site' => 'View Site',
	'net_admin_earnings' => 'Net Earnings (Admin)',
	'users' => 'Users',
	'statistic_of_the_month' => 'Statistic of the month',
	'revenue_today' => 'REVENUE TODAY',
	'revenue_this_week' => 'REVENUE THIS WEEK',
	'revenue_this_month' => 'REVENUE THIS MONTH',
	'new_registered_users' => 'New registered users',
	'view_all' => 'View All',
	'latest_subscriptions' => 'Latest Subscriptions',
	'latest_content_payments' => 'Latest Content Payments',
	'subscribed_u' => '<a href="' . $base_url . '{payedSubscriberUserName}">{payedSubscriberUserFullName}</a> subscribed to <a href="' . $base_url . '{payerSubscriberUserName}">{payerSubscriberUserFullName}</a>',
	'payedcontent_u' => '<a href="' . $base_url . '{payedSubscriberUserName}">{payedSubscriberUserFullName}</a> purchased <a href="' . $base_url . '{payerSubscriberUserName}">{payerSubscriberUserFullName}</a>\'s content',
	'general_settings' => 'General Settings',
	'site_name' => 'Site Name',
	'site_title' => 'Site Title',
	'site_description' => 'Site Description',
	'site_keywords' => 'Keywords',
	'billing_informations' => 'Billing Informations',
	'campany' => 'Campany',
	'country' => 'Country',
	'city' => 'City',
	'business_address' => 'Business Address',
	'post_code' => 'Post Code',
	'vat' => 'Vat',
	'site_logo' => 'Site Logo',
	'recommended_logo_sizes' => 'Logo height must be 45px , recommended with 135px',
	'upload_logo' => 'Upload Logo',
	'upload_favicon' => 'Upload Favicon',
	'favicon_size_must_be' => 'Favicon size must be 128x128px',
	'favicon' => 'Favicon',
	'upload_size_limit' => 'Upload File Size Limit',
	'post_length' => 'Post Length',
	'attantion_server_default_maximum_file_upload_size' => 'IMPORTANT: Please pay attention to your server\'s default maximum file upload size.',
	'limit_character' => '{chLimit} Character',
	'character' => 'Character',
	'show_number_of_post' => 'Number of post show',
	'also_displayed_whe_page_scrolled' => 'It is also the number of posts that will be displayed when the page is scrolled.',
	'max_character' => 'It is the maximum character value that can be written to a post.',
	'show_number_of_paginaton' => 'Show number of pagination',
	'manage_features' => 'Manage Features',
	'maintenance_title' => 'SORRY! WE ARE UNDER SCHEDULED MAINTENANCE',
	'maintenance_desc' => 'Our website is currently undergoing scheduled maintenance, will be right back in a few minutes. Thank you for patientce.',
	'website_settings' => 'Website Settings',
	'maintenance_mode' => 'Maintenance Mode',
	'maintenance_mode_not' => 'While your website is in maintenance mode, administrators and moderators, if any, can login. All other users will view the maintenance page.',
	'email_verification_status' => 'Email Verification',
	'email_verification_not' => 'A confirmation mail is sent to newly registered users. There is a confirmation link sent by the system in the confirmation mail, when the member is clicked on this link, the user\'s account is activated.',
	'register' => 'Register',
	'allow_disallow_register' => 'Allows registration of new members on your website.',
	'ip_limit' => 'IP Limit',
	'ip_limit_not' => 'A person can only create two accounts on a single IP address.',
	'main_language' => 'Main Language',
	'main_lang_not' => 'Your selection is the main language that will be displayed when members register or visit the site.',
	'allowed_file_extension' => 'Allowed file extensions',
	'separated_with' => 'Separated with comma,',
	'file_extensions_for_approval' => 'File extensions valid for approval',
	'server_type' => 'Server type',
	'smtp_host' => 'SMTP Host',
	'smtp_username' => 'SMTP Username',
	'smtp_password' => 'SMTP Password',
	'smtp_port' => 'SMTP Port',
	's3_status' => 's3 Status',
	's3_status_not' => '<li>Before enabling Amazon S3, make sure you upload the whole "uploads/" folder to your bucket.</li><li>Before disabling Amazon S3, make sure you download the whole "uploads/" folder to your server.</li>',
	's3Bucket' => 'Amazon Bucket Name',
	's3Key' => 'Amazon S3 Key',
	's3sKey' => 'Amazon S3 Secret Key',
	'user' => 'User',
	'approve_or_decline' => 'Edit / Approve / Decline',
	'see_post' => 'See Post',
	'add_not_to_the_post_owner' => 'Add a note to the post owner (<span>optional</span>)',
	'write_your_not' => 'Write your note! (Optional)',
	'approve' => 'Approve',
	'be_carefuly_check_post' => 'Before you mark it, be sure to carefully check the post. When you Approve, you do not need to write a note to the person. Because a approved notification is sent to him.',
	'reject' => 'Reject',
	'rejected_not' => 'Write a note telling you why you reject the post. (Recommended)',
	'decline' => 'Decline',
	'decline_not' => 'Write a note telling you why you declined the post. (Recommended)',
	'no_post_pending_approval' => 'There are no posts pending approval.',
	'no_user_found' => 'There are no registered members yet.',
	'delete' => 'Delete',
	'post_owner' => 'Post Owner',
	'post_type' => 'Post Type',
	'post_shared_time' => 'Date',
	'actions' => 'Actions',
	'all' => 'Everyone',
	'pending_approve' => 'Pending Approve',
	'sure_to_delete_post' => 'Hi Admin! Are you sure want to delete this post? There is no undo!',
	'design' => 'Design',
	'custom_css_js' => 'Custom CSS/JS',
	'manageicons' => 'Manage SVG Icons',
	'header_custom_css_styles' => 'Header Custom CSS styles',
	'header_custom_javascript' => 'Header Custom Javascript',
	'footer_custom_javascript' => 'Footer custom Javascript',
	'edit_svg_code' => 'Edit SVG',
	'paste_your_svg_code_here' => 'Paste your SVG code here...',
	'save_new_svg' => 'Save new SVG',
	'create_a_new_svg_icon' => 'Create a new SVG Icon',
	'manage_point_feature' => 'Manage Point Feature',
	'point_packages_settings' => 'Point Packages Settings',
	'edit_package' => 'Edit Package',
	'plan_key' => 'Package Key <li>When you change this key name, you must also change the Package key in the language files.</li><li>Your keyword must not contain spaces</li>',
	'plan_point' => 'Package Point',
	'plan_fee' => 'Point Amount',
	'create_a_new_package' => 'Create a new Package',
	'new_plan_key' => 'Package Key <li>When you add this key name, you must also add this Package key in the language files.</li><li>Your keyword must not contain spaces</li>',
	'plan_key_ex' => 'e.g: golden',
	'plan_point_amount_ex' => 'e.g: 300',
	'plan_amount_ex' => 'e.g: 200',
	'plan_key_warning' => 'Package key must not be empty',
	'plan_point_warning' => 'Minimum point can be {minimumPointLimit}',
	'plan_point_amount_warning' => 'Minimum point Amount can be ' . $currencys[$defaultCurrency] . '1 and Maximum point Amount can be ' . $currencys[$defaultCurrency] . '{maximumPointAmountLimit}',
	'plan_status' => 'Status',
	'must_contain_all_plan_informations' => 'To create a new plan table, you need to enter all the information completely.',
	'edit_plan' => 'Edit',
	'delete_plan' => 'Delete',
	'sure_want_to_delete_this_plan' => 'Hi Admin! Are you sure want to delete this package plan? There is no undo!',
	'create_a_new_lang' => 'Create a new language',
	'new_lang_not' => 'This abbreviation is also the name of your language file. So when you add a new language, the abbreviation name you add must be the same as your filename. E.g. : Your abbreviation name is xx . Then the filename in lang/ xx.php',
	'abbreviation' => 'Abbreviation: ',
	'edit_language' => 'Edit Language',
	'lang_abbreviation' => 'Language Abbreviation',
	'edit_lang_not' => '<strong>IMPORTANT:</strong> <li>You must place the name of the correct folder located at: lang/</li> <li>This abbreviation is also the name of your language file. So when you add a new language, the abbreviation name you add must be the same as your filename.</li>',
	'lang_abbreviation_ex' => 'e.g: ch',
	'lang_global_warning' => 'You left the abbreviation field blank.',
	'lang_abbreviation_warning' => '<strong style="color:#000000;">Language abbreviation</strong> name can never be blank!',
	'not_mach_abbreviation' => 'A matching abbreviation name was not found.',
	'add_new_language' => 'Add New Language',
	'used_this_abbreviation_key' => 'You have previously used the abbreviated language keyword you are trying to add for another language. Please enter a different abbreviated language keyword.',
	'delete_language' => 'Delete Language',
	'delete_note_lang' => 'Hi Admin! Are you sure you want to delete this language? Instead, it would be correct to deactivate this language.',
	'make_sure_added_in_current_lang_array' => '<li>Please be sure to include this language abbreviation in the language file you are currently using.</li><li>Open file langs/' . $defaultLanguage . '.php and fined the array $LANGNAME add your abbreviate name in array.</li><li>Open other language packs from langs file and do the same.</li>',
	'manage_users' => 'Manage Users',
	'creator_requests' => 'Creator Verification Requests',
	'user' => 'User',
	'user_type' => 'User Type',
	'user_creator_type' => 'User Creator Type',
	'registered_time' => 'Registered at',
	'edit_user_infos' => 'Edit',
	'verification_status' => 'Verification Status',
	'see_profile' => 'See profile',
	'normal_user' => 'Normal user',
	'admin' => 'Admin',
	'premium_user' => 'Verified',
	'not_verified' => 'Not Verified',
	'edit_user_profile_details' => 'Edit User',
	'verified_status' => 'Verified Status',
	'verification_pending' => 'Verification pending',
	'moderator' => 'Moderator',
	'role' => 'User Role',
	'wallet' => 'Wallet',
	'login_as_user' => 'Login As user',
	'delete_user' => 'Delete User',
	'do_not_have_this_authority' => 'You are not authorized to automatically login to another user\'s account. You are currently logged in as a demo manager. This is why your request cannot be fulfilled.',
	'are_you_sure_want_to_delete_this_user' => 'Hi Admin! Are you sure want to delete this user ? There is no undo!',
	'request_time' => 'Request Time',
	'delete_verification_request' => 'Delete Verification Request',
	'sure_to_delete_verification_request' => 'Hi Admi! Are you sure want to delete this Verification Request ?',
	'be_carefuly_check_verifiction' => 'Before you mark it, be sure to carefully check the request.',
	'rejected_verification_not' => 'Write a note telling you why you reject the request. (Recommended)',
	'add_not_to_the_request_owner' => 'Add a note to the request owner (<span>optional</span>)',
	'approve_or_reject_verification_request' => 'Approve or Reject or Delete Verification Request',
	'congratulations_approved' => 'Congratulations!',
	'congrat_approved_not' => 'Congratulations, your profile has received Creator approval. You need to make some settings. <a href="' . $base_url . 'creator/becomeCreator">Click</a>',
	'sorry_rejected' => 'Sorry!',
	'sorry_you_are_rejected' => 'Your request to become a creator has been denied.',
	'request_rejected' => 'Rejected',
	'pages' => 'Pages',
	'page_title' => 'Page Title',
	'seo_url' => 'SEO / URL',
	'edit_page' => 'Edit Page',
	'view_page' => 'View Page',
	'page_content' => 'Page Content',
	'create_a_new_page' => 'Create a New Page',
	'delete_page' => 'Delete Page',
	'are_you_sure_want_to_delete_this_page' => 'Hi Admin! Are you sure want to delete this page? There is no undo!',
	'any_questions' => 'Any Questions?',
	'do_not_hesitate' => 'Don\'t hesitate!',
	'msg' => 'Message',
	'your_message' => 'Your Message',
	'your_message_sended_success' => 'Your message sended success!',
	'alread_sended_contact_email' => 'You have already sended email from us! Please wait an answer. We will back you as soon as possible!',
	'please_try_again_later_contact' => 'You can not send a message right now! Please try again later.',
	'manage_stickers' => 'Stickers',
	'sticker_url' => 'Sticker URL',
	'sticker' => 'Sticker',
	'add_new_sticker' => 'Add New Sticker Url',
	'edit_sticker' => 'Edit Sticker',
	'paste_your_sticker_url_here' => 'Paste your Sticker URL here',
	'save_sticker' => 'Save Sticker',
	'payment_methods' => 'Payment Methods',
	'payment_settings' => 'Payment Settings',
	'paypal_payment' => 'PayPal',
	'bitpay_payment' => 'BitPay',
	'stripe_payment' => 'Stripe',
	'authorizenet_payment' => 'Ahurhorize.Net',
	'iyzico_payment' => 'IyziCo',
	'razorpay_payment' => 'Razorpay',
	'paystack_payment' => 'PayStack',
	'default_currency' => 'Default Currency',
	'important_for_subscription_currency_selection_not' => 'IMPORTANT: This selection is for the stripe subscription system.',
	'fee_comission' => 'Fee commission (Admin Earnings)',
	'fee_mossion_not' => 'It is the commission that the Admin will earn from point sales and subscription sales.',
	'min_sub_amount_weekly' => 'Minimum subscription Amount (weekly)',
	'min_sub_amount_monthly' => 'Minimum subscription Amount (monthly)',
	'min_sub_amount_yearly' => 'Minimum subscription Amount (yearly)',
	'min_point_amount' => 'Minimum Point Amount',
	'max_point_amount' => 'Maximum Point Amount',
	'how_much_one_point' => 'How much is 1 Point (' . $currencys[$defaultCurrency] . ')',
	'minimum_withdrawal_amount_set' => 'Minimum withdrawal amount',
	/*PayPal*/
	'paypal_status' => 'PayPal Status',
	'paypal_status_not' => 'When PayPal status is active, members can buy points to their wallets via paypal.',
	'sandbox_mode' => 'Sandbox',
	'live_mode' => 'Live Mode',
	'paypal_sandbox_business_email' => 'PayPal Sandbox Business Email',
	'paypal_product_business_email' => 'PayPal Product Business Email',
	'paypal_currency' => 'PayPal Currency',
	'make_sure_for_paypal' => 'IMPORTANT: Make sure PayPal accept currency.',
	'test_mode' => 'Test Mode',
	/*Bitpay*/
	'bitpay_status' => 'BitPay Status',
	'bitpay_status_not' => 'When BitPay status is active, members can buy points to their wallets via BitPay.',
	'bitpay_notification_email' => 'Notification Email',
	'bitpay_password' => 'Password',
	'bitpay_pairing_code' => 'Pairing Code',
	'bitpay_label' => 'Label',
	'bitpay_currency' => 'BitPay Currency',
	'make_sure_for_bitpay' => 'IMPORTANT: Make sure bitPay accept currency.',
	/*STripe*/
	'stripe_status' => 'Stripe Status',
	'stripe_status_not' => 'When Stripe status is active, members can buy points to their wallets via Stripe.',
	'stripe_test_secret_key' => 'Test Secret Key',
	'stripe_test_public_key' => 'Test Public Key',
	'stripe_live_secret_key' => 'Live Secret key',
	'stripe_live_public_key' => 'Live Public Key',
	'stripe_crncy' => 'Stripe Currency',
	'make_sure_for_stripe' => 'IMPORTANT: Make sure Stripe accept currency.',
	/*Authorize*/
	'authorizenet_status' => 'Authorize.Net Status',
	'authorizenet_crncy' => 'Authorize.Net Currency',
	'authorizenet_status_not' => 'When Authorize.Net status is active, members can buy points to their wallets via Authorize.Net.',
	'authorizenet_test_ap_id' => 'Test APP ID',
	'authorizenet_test_transaction_key' => 'Test Transaction KEY',
	'authorizenet_live_api_id' => 'Live APP ID',
	'authorizenet_live_transaction_key' => 'Live Transaction KEY',
	'make_sure_for_authorizenet' => 'IMPORTANT: Make sure Authorize.Net accept currency.',
	/*iyziCo*/
	'iyzico_status' => 'IyziCo Status',
	'iyzico_crncy' => 'IyziCo Currency',
	'iyzico_status_not' => 'When IyziCo status is active, members can buy points to their wallets via IyziCo.',
	'iyzico_testing_secret_key' => 'Test Secret Key',
	'iyzico_testing_api_key' => 'Test API Key',
	'iyzico_live_api_key' => 'Live API Key',
	'iyzico_live_secret_key' => 'Live Secret Key',
	'make_sure_for_iyzico' => 'IMPORTANT: Make sure IyziCo accept currency.',
	/*razorpay*/
	'razorpay_status' => 'RazorPay Status',
	'razorpay_crncy' => 'RazorPay Currency',
	'razorpay_status_not' => 'When RazorPay status is active, members can buy points to their wallets via RazorPay.',
	'razorpay_testing_key_id' => 'Test Secret Key ID',
	'razorpay_testing_secret_key' => 'Test Key ID',
	'razorpay_live_key_id' => 'Live Key ID',
	'razorpay_live_secret_key' => 'Live Secret Key ID',
	'make_sure_for_razorpay' => 'IMPORTANT: Make sure RazorPay accept currency.',
	/*payStack*/
	'paystack_status' => 'PayStack Status',
	'paystack_crncy' => 'PayStack Currency',
	'paystack_status_not' => 'When PayStack status is active, members can buy points to their wallets via PayStack.',
	'paystack_testing_secret_key' => 'Test Secret Key',
	'paystack_testing_public_key' => 'Test Public Key',
	'paystack_live_secret_key' => 'Live Secret Key',
	'pay_stack_liive_public_key' => 'Live Public Key',
	'make_sure_for_paystack' => 'IMPORTANT: Make sure PayStack accept currency.',
	'social_logins' => 'Social Logins',
	'social_login_status_not' => 'When status is active, members can login with {sKey} .',
	'manage_payments' => 'Manage Payments',
	'manage_withdrawals' => 'Manage Withdrawals',
	'manage_subscription_payments' => 'Manage Subscription Payment',
	'paid' => 'Paid',
	'payment_method' => 'Payment Method',
	'decline_payment_request' => 'Decline Payment Request',
	'sure_to_decline_this_payment' => 'Hi Admin! Are you sure you want to decline this payment request? The member\'s money will be returned to their wallet account.',
	'ok_decline' => 'Yes Decline',
	'delete_payment_request' => 'Delete Payment Request',
	'sure_to_delete_payment_request' => 'Hi Admin! Are you sure want to delete this payment request?',
	'sure_delete' => 'Yes Delete',
	'payed' => 'Paid',
	'register_disabled' => 'We are currently unable to register a new member. Please try again in a few minutes.',
	'your_payment_successfull' => 'Your payment is successfull',
	'forgot_password' => '' . $siteName . ' || Forgot Password',
	'forgot_pass_not' => 'You sent us a request that you forgot my password. Please click the link below to reset your password. If you haven\'t done this, ignore this email.',
	'check_your_email' => 'We have sent you a reset mail. Please check your e-mail address. Don\'t forget to check your Junk folder.',
	'this_email_not_registered' => 'This e-mail address is not registered.',
	'email_send_closed' => 'Email delivery service is currently down, please try again later.',
	'reset_your_password' => 'Reset password',
	'reset_pass_not' => 'Your old password is the same until you perform the reset. If you remembers your password, you can ignore this action.',
	'your_new_pass' => 'New Password',
	'write_your_new_pass' => 'Write your new password',
	're_new_pass' => 'Re-New Password',
	're_re_new_pass' => 'Retype your new password',
	'reset_now' => 'Reset Now',
	'your_pass_changed_success_login' => 'Your password has been changed successfully. You can login with your new password.',
	'create_advertisement' => 'Create a Advertisement',
	'ads_title' => 'Advertisement Title',
	'ads_description' => 'Advertisement Description',
	'ads_image' => 'Advertisement Image',
	'u_ads_image' => 'Upload Image',
	'recommend_ads_image' => '270px width 170px height to get a good view',
	'ads_redirect_url' => 'Ads Redirect Url',
	'advertisement_' => 'Advertisement',
	'managa_advertisements' => 'Manage Advertisements',
	'edit_ads' => 'Edit Advertisement',
	'delete_advertisement' => 'Delete Advertisement',
	'are_you_sure_delete_ads' => 'Are you sure want to delete this Advertisement ?',
	'dont_have_ads_yet' => 'You don\'t have any sponsored ads registered yet. <a href="' . $base_url . 'admin/create_advertisement">Click to create an ad.</a>',
	'all_fields_must_be_filled' => 'All fields must be filled.',
	'must_be_enter_image_url_for_sticker' => 'You must enter an image url for the sticker.',
	'url_is_not_valid' => 'URL is not valid',
	'sticker_url_must_be' => 'URL is not valid. e.g: https://www.websiteurl.com/imagename.png',
	'delete_sticker' => 'Delete Sticker',
	'sure_to_delete_this_sticker' => 'Are you sure want to delete this sticker ?',
	'sticker_id_not_available' => 'Sticker ID is not available.',
	'you_must_fill_all_ads_to_public' => 'You must fill in all fields completely in order to publish the ad.',
	'upload_ads_image_not' => 'You have not uploaded an image for the advertisement. When you upload the image you will see a green check mark next to the button',
	'updated_successfully' => 'Updated Successfully!',
	'not_live_file_extensions_blank' => 'You must not leave allowed file extensions blank. these extensions control which files members upload.',
	'not_live_approved_file_extension' => 'It determines the extensions of the files to be uploaded by those who want to be approved. This field is required, you must not leave it blank.',
	'saved_successfully' => 'Saved Successfully!',
	'ups_you_forgot_to_add_svg_code' => 'Ups! You forgot to add your SVG code.',
	'please_use_svg_code' => 'Please use SVG code!',
	'save_failed' => 'Save failed, please try again later.',
	'page_title_please' => 'Page Title should not be empty',
	'seo_url_please' => 'SEO Url should not be empty',
	'alert_for_sticker_url' => 'It looks like you haven\'t entered a url with an image extension. Url needs to end with jpeg, jpg, png, gif extension. Please make sure the url path is correct. e.g: https://www.websiteurl.com/imagename.png',
	'no_empty_no_zero' => 'All values can be at least 1 and no values should be left blank.',
	'please_add_ads_title' => 'Please add a Advertisement Title',
	'add_saved' => 'Ad saved. It is inactive for final checks. To view it, go to the <a href="' . $base_url . 'admin/managa_advertisements">Manage advertisements</a> page.',
	'important_for_login_as_user' => '<strong>IMPORTANT:</strong> If you click <strong>Login As User</strong> button, The account you are currently logged in will be logged out.',
	'warning_approve_profile_choose' => 'If you approve the user, select the Approve button, if not, choose the Reject option.',
	'my_payments' => 'My Payments',
	'paid_to' => 'Paid to',
	'point' => 'Point',
	'your_age_must_be' => 'Your age must be over 18+',
	'full_name_must_be' => 'Full name must be minimum 5 and maximum 16 characters.',
	'nothing_to_show_about_payment_history' => 'There is nothing to show in the payment history yet.',
	'nothing_to_show_about_payout_history' => 'There is nothing to show in the payout history yet.',
	'nothing_to_show_about_subscribed_your_profile' => 'Nobody is seen who has subscribed to your profile yet.',
	'fill_all_google_requirements' => 'Fill in all required keys for Google login.',
	'fill_all_twitter_requirements' => 'Fill in all required keys for Twitter login.',
	'no_withdrawal_request_yet' => 'There is no withdrawal request yet.',
	'no_creator_waiting_subscription_payment' => 'No creator pending subscription payment',
	'payment_request_no_longer_available' => 'This payment request is no longer available.',
	/*Version v1.1*/
	'stripe_payment_subs' => 'Stripe(Subscription)',
	'subscription_feature_status' => 'Subscription Status',
	'no_one_will_make_new_subs' => 'If you turn this feature off, no one will be able to make a new subscription.',
	'giphy_settings' => 'Giphy API',
	'g_api_key' => 'Giphy API key',
	'enter_valid_giphy_key' => 'Please enter a valid giphy API key.',
	'paid_live_streamings' => 'Paid Live Streamings',
	'must_pay_for_watch' => 'A fee is required for entry',
	'free_live_streams' => 'Free live streams',
	'free_entry' => 'Entrance is free',
	'start_new_paid_live_stream' => 'Start paid live stream',
	'start_new_free_live_stream' => 'Start a free live stream',
	'create_a_paid_live_streaming' => 'Create a Paid Live Streaming',
	'create_a_free_live_streaming' => 'Create a Free Live Streaming',
	'give_this_live_stream_a_name' => 'Give this live stream a name',
	'free_live_not' => 'Free live streams are timed and can only be created once a day.Your live broadcast time is ' . $freeLiveTime . ' minutes per day.',
	'create' => 'Create',
	'already_created_live_breadcast' => 'You have already started a 30-minute live stream. Do you want to continue the existing live stream?',
	'continue' => 'Continue',
	'filled_daily_live_broadcast' => 'You have filled your daily live broadcast limit. You can create a live stream of ' . $freeLiveTime . ' minutes again tomorrow.',
	'minutes_left' => 'min',
	'entrace_fee' => 'Entrance fee',
	'point_wanted_for_streaming' => 'How much do you charge for people to access this live stream? One point: $' . $onePointEqual . '',
	'live_stream_not_for_paid' => 'People who subscribe to your profile can log in to this live stream free of charge.',
	'paying_point_for_live_streaming' => 'You are currently paying to see the live stream.',
	'join_the_live_broadcast' => 'Join the live broadcast',
	'min_stream_fee' => 'You can request at least ' . $minimumLiveStreamingFee . ' points for the entrance fee.',
	'enter_live_stream_title' => 'Enter a title for your live stream.',
	'please_fill_all_for_live_stream' => 'Please fill in all fields to create a live stream.',
	'only_creators_' => 'Only creators can create paid live streams.',
	'stream_name_wrning' => 'Streaming name can be a minimum of 5 and a maximum of 32 characters.',
	'no_live_streams' => 'There are no live streams to view.',
	'join' => 'Join',
	'live_streaming_settings' => 'Live Streaming Settings',
	'live_s_status' => 'Live Streaming Status',
	'live_s_not' => 'When Live Streaming is active, please make sure your agora.io api keys below are correct. Live broadcast will not work if that is the case.',
	'free_live_stream_time' => 'Free live stream time (minutes)',
	'not_for_time' => 'This restriction applies to non-creator members.',
	'agora_app_id' => 'Agora APP ID',
	'agora_certificate' => 'Agora Certificate',
	'agora_customer_id' => 'Agora Customer ID',
	'all_information_need_filled' => 'All information needs to be filled in while in open mode.',
	'live_stream_price_point' => 'Live stream price (lowest)(point)',
	'ffmpeg_path' => 'FFMPEG path',
	'make_sure_ffmpeg_activated' => 'Make sure your server has activated the FFMPEG feature.',
	'the_hashtags' => 'Hashtags',
	/*LANDING PAGE*/
	'landing_title' => 'Make an Income Doing What You Love',
	'landing_desc' => 'The easy way to make money. Earn money from subscriptions, premium posts and paid live streams.',
	'claim' => 'Claim',
	'animation_box_live_streaming' => 'Live Streaming',
	'animation_box_comissions' => 'Comissions',
	'animation_box_premium_content' => 'Premium Content',
	'animation_box_subscriptions' => 'Subscriptions',
	'our_features_title' => '<span>Our features</span> to <span class="clr">develop your community</span>',
	'l_premium' => 'Premium',
	'l_exlusive_contents' => 'Post <strong>exclusive contents</strong> to the unit. Choose a price and even offer promotions !',
	'fan_club' => 'Fan Club',
	'fan_club_desc' => 'Add unique content for your fans by feeding your <strong>Private flow</strong> and build a strong community!',
	'l_live_streamings' => 'Live Streamings',
	'l_live_streamings_desc' => 'Create <strong>paid private live streams</strong> for people based on your availability.',
	'l_private_content' => 'Private Contents',
	'l_private_content_desc' => 'Does your community have any special requests? <strong>Customize your contents</strong> to increase your revenue!',
	'l_private_messages' => 'Private Messages',
	'l_private_messages_desc' => 'Message people privately, <strong>increase your interaction</strong> with them.',
	'l_becomea_creator' => 'Become a Creator',
	'l_join_our_community_now_and_start_growing_users' => 'Join our community now and start growing yours while generating money easily! Creative can use many features. For example, creators can earn money. What you need to do for this is very simple. Register and click the Become a Creator button.Making money is not far off. Come on, be a creator.',
	'creators_earning_simulator' => 'Creators Earnings Simulator',
	'calculate_how_much_can_earn' => 'Calculate how much you can earn based on the number of followers and their rate',
	'l_number_of_followers' => 'Number of followers?',
	'l_monthly_subscription_price' => 'Monthly subscription price?',
	'per_month_calculate_earn' => 'You could earn an estimated <span id="estimatedEarn">' . $currencys[$defaultCurrency] . '95.00</span> ' . $defaultCurrency . ' per month*',
	'not_for_calculate' => '* Based on an estimate of ' . $adminFee . '% of your followers who subscribe (Does not include payment processor fees)',
	'animatesignup' => '<span class="_1u5W_ landing-sticky-footer-in-color-click">' . $siteName . '</span> <span class="_1u5W_">i</span><span class="_1u5W_">s</span><span class="_1u5W_"> </span><span class="_1u5W_">f</span><span class="_1u5W_">r</span><span class="_1u5W_">e</span><span class="_1u5W_">e</span><span class="_1u5W_">!</span><span class="_1u5W_"> </span><span class="_1u5W_">C</span><span class="_1u5W_">r</span><span class="_1u5W_">e</span><span class="_1u5W_">a</span><span class="_1u5W_">t</span><span class="_1u5W_">e</span><span class="_1u5W_"> </span><span class="_1u5W_">a</span><span class="_1u5W_"> </span><span class="_1u5W_">p</span><span class="_1u5W_">r</span><span class="_1u5W_">o</span><span class="_1u5W_">f</span><span class="_1u5W_">i</span><span class="_1u5W_">l</span><span class="_1u5W_">e</span><span class="_1u5W_"> </span><span class="_1u5W_">a</span><span class="_1u5W_">n</span><span class="_1u5W_">d</span><span class="_1u5W_"> </span><span class="_1u5W_">f</span><span class="_1u5W_">u</span><span class="_1u5W_">n</span><span class="_1u5W_">d</span><span class="_1u5W_"> </span><span class="_1u5W_">y</span><span class="_1u5W_">o</span><span class="_1u5W_">u</span><span class="_1u5W_">r</span><span class="_1u5W_"> </span><span class="_1u5W_">p</span><span class="_1u5W_">a</span><span class="_1u5W_">s</span><span class="_1u5W_">s</span><span class="_1u5W_">i</span><span class="_1u5W_">o</span><span class="_1u5W_">n</span><span class="_1u5W_">.</span><a href="' . $base_url . 'register">Sign up Now!</a>',
	'manage_landing_page' => 'Manage Landing Page',
	'update_landing_page_images' => 'Update Landing Page Images',
	'image_one' => 'Image 1',
	'update_image_one' => 'Update Image 1',
	'image_two' => 'Image 2',
	'update_image_two' => 'Update Image 2',
	'image_three' => 'Image 3',
	'update_image_three' => 'Upload Image 3',
	'image_four' => 'Image 4',
	'update_image_four' => 'Upload Image 4',
	'image_five' => 'Image 5',
	'update_image_five' => 'Upload Image 5',
	'image_six' => 'Image 6',
	'update_image_six' => 'Upload Image 6',
	'image_seventh' => 'Image 7',
	'update_image_seventh' => 'Upload Image 7',
	'image_bg' => 'Image 8',
	'update_image_bg' => 'Upload Image 8',
	'image_frnt' => 'Image 9',
	'update_image_frnt' => 'Upload Image 9',
	'landing_question_answer' => 'Landing Page Q&A',
	'create_a_new_question_answer' => 'Create a New Q&A',
	'question' => 'Question',
	'edit_qa' => 'Edit Q&A',
	'delete_qa' => 'Delete Q&A',
	'are_you_sure_want_to_delete_this_qa' => 'Are you sure want to delete this Q&A?',
	'save_new_question_answer' => 'Save New Q&A',
	'answer' => 'Answer',
	'save_edited_qa' => 'Save Edit Q&A',
	'question_and_answer_must_be_filled' => 'Question and answer must be filled.',
	'finish_subscription' => 'Finish Subscription',
	'are_you_sure_want_to_finish_subscription' => 'Are you sure want to finish subscription to this user?',
	'not_become_creator' => 'You must be an approved creator for your profile to be displayed on the creators page. <a href="'.$base_url.'creator/becomeCreator">Become a Creator</a> to be approved',
	'ccbill_subscription_settings' => 'CCBILL Payment (Subscription)',
	'ccbill_status' => 'CCBILL status',
	'ccbill_account_number' => 'CCBILL Account Number',
	'ccbill_subaccount_number' => 'CCBILL Subaccount Number',
	'ccbill_flexform_id' => 'CCBILL Flex Form ID',
	'ccbill_salt_key' => 'CCBILL Salt Key',
	'ccbill_currency' => 'CCBILL Currency', 
	'make_sure_for_ccbill' => 'IMPORTANT: Make sure CCBILL accept currency.',
	'details' => 'Details',
	'withdrawal_details' => 'Withdrawal Details',
	'close' => 'Close',
	'amount_requested' => 'Amount requested',
	'payment_address' => 'Payment Address',
	'requested_date' => 'Request date',
	'payment_date' => 'Payment Date',
	's3_storage_settings' => 'S3 Storage Settings',
	'digital_ocean_settings' => 'DigitalOcean Storage Settings',
	'docean_status' => 'DigitalOcean Status',
	'docean_status_not' => '<li>Before enabling DigitalOcean, make sure you upload the whole "uploads/" folder to your bucket.</li><li>Before disabling DigitalOcean, make sure you download the whole "uploads/" folder to your server.</li>',
	'docean_ducket' => 'DigitalOceal Bucket',
	'docean_key' => 'DigitalOcean Key',
	'oceansecret_key' => 'DigitalOcean Secret Key',
	'oceanregion' => 'DigitalOcean Region',
	/*Version 2.3*/
	'point_purchasing' => 'Point Purchaseing',
	'point_purchasing_from' => 'You are currently purchasing points from '.$base_url.'.',
	'cookie_title' => '🍪 Accept cookies & privacy policy?',
	'cookie_desc' => 'This site uses cookies, by continuing to use the service, you accept our use of cookies Cookies Policy, <a href="'.$base_url.'cookies;?>">Cookie Policy</a>',
	'not_use_ffmpeg' => 'ffmpeg Installed',
	'use_ffmpeg' => 'ffmpeg not Installed',
	'ffmpeg_status' => 'ffmpeg Status',
	'unsupported_video_format' => 'Unsupported video format. The uploaded video can only be in mp4 format.',
	'custom_tumbnail' => 'Custom Tumbnail',
	'not_allowed_usernames' => 'Not allowed usernames',
	'suggested_creators' => 'Suggested Creators'
);

$creatorConditions = array(
	'conditions_document' => 'If you are reading this page, this means that your account is now activated for monetization. Congratulations.<p>The Website will make every effort to reply as soon as possible to the Creator concerning their request to be added to the Creator service. </p><p>Once the Company approves your profile, the Creator can decide whether their Content will be visible to all Users or just their Fans. </p> <p>A tick will now appear next to your nickname. At the same time, an icon will appear indicating that you are a creator.</p> <p>The page that will appear when you click the forward button at the bottom of this page will help you activate some of the buttons in your profile.</p>',
);

$PROFILE_CATEGORIES = array(
	'instagramer' => 'Instagramer',
	'youtuber' => 'Youtuber',
	'influencer' => 'Influencer',
	'financial_tipper' => 'Financial Tipper',
	'designer' => 'Designer',
	'developer' => 'Developer'
);

$LANGNAME = array(
	'eng' => 'English',
	'tr' => 'Turkish',
	'fr' => 'French',
);

$COUNTRIES = array(
	"0" => "Select Country",
	"AF" => "Afghanistan",
	"AX" => "Åland Islands",
	"AL" => "Albania",
	"DZ" => "Algeria",
	"AS" => "American Samoa",
	"AD" => "AndorrA",
	"AO" => "Angola",
	"AI" => "Anguilla",
	"AQ" => "Antarctica",
	"AG" => "Antigua and Barbuda",
	"AR" => "Argentina",
	"AM" => "Armenia",
	"AW" => "Aruba",
	"AU" => "Australia",
	"AT" => "Austria",
	"AZ" => "Azerbaijan",
	"BS" => "Bahamas",
	"BH" => "Bahrain",
	"BD" => "Bangladesh",
	"BB" => "Barbados",
	"BY" => "Belarus",
	"BE" => "Belgium",
	"BZ" => "Belize",
	"BJ" => "Benin",
	"BM" => "Bermuda",
	"BT" => "Bhutan",
	"BO" => "Bolivia",
	"BA" => "Bosnia and Herzegovina",
	"BW" => "Botswana",
	"BV" => "Bouvet Island",
	"BR" => "Brazil",
	"IO" => "British Indian Ocean Territory",
	"BN" => "Brunei Darussalam",
	"BG" => "Bulgaria",
	"BF" => "Burkina Faso",
	"BI" => "Burundi",
	"KH" => "Cambodia",
	"CM" => "Cameroon",
	"CA" => "Canada",
	"CV" => "Cape Verde",
	"KY" => "Cayman Islands",
	"CF" => "Central African Republic",
	"TD" => "Chad",
	"CL" => "Chile",
	"CN" => "China",
	"CX" => "Christmas Island",
	"CC" => "Cocos (Keeling) Islands",
	"CO" => "Colombia",
	"KM" => "Comoros",
	"CG" => "Congo",
	"CD" => "Congo, Democratic Republic",
	"CK" => "Cook Islands",
	"CR" => "Costa Rica",
	"CI" => "Cote D\"Ivoire",
	"HR" => "Croatia",
	"CU" => "Cuba",
	"CY" => "Cyprus",
	"CZ" => "Czech Republic",
	"DK" => "Denmark",
	"DJ" => "Djibouti",
	"DM" => "Dominica",
	"DO" => "Dominican Republic",
	"EC" => "Ecuador",
	"EG" => "Egypt",
	"SV" => "El Salvador",
	"GQ" => "Equatorial Guinea",
	"ER" => "Eritrea",
	"EE" => "Estonia",
	"ET" => "Ethiopia",
	"FK" => "Falkland Islands (Malvinas)",
	"FO" => "Faroe Islands",
	"FJ" => "Fiji",
	"FI" => "Finland",
	"FR" => "France",
	"GF" => "French Guiana",
	"PF" => "French Polynesia",
	"TF" => "French Southern Territories",
	"GA" => "Gabon",
	"GM" => "Gambia",
	"GE" => "Georgia",
	"DE" => "Germany",
	"GH" => "Ghana",
	"GI" => "Gibraltar",
	"GR" => "Greece",
	"GL" => "Greenland",
	"GD" => "Grenada",
	"GP" => "Guadeloupe",
	"GU" => "Guam",
	"GT" => "Guatemala",
	"GG" => "Guernsey",
	"GN" => "Guinea",
	"GW" => "Guinea-Bissau",
	"GY" => "Guyana",
	"HT" => "Haiti",
	"HM" => "Heard Island and Mcdonald Islands",
	"VA" => "Holy See (Vatican City State)",
	"HN" => "Honduras",
	"HK" => "Hong Kong",
	"HU" => "Hungary",
	"IS" => "Iceland",
	"IN" => "India",
	"ID" => "Indonesia",
	"IR" => "Iran",
	"IQ" => "Iraq",
	"IE" => "Ireland",
	"IM" => "Isle of Man",
	"IL" => "Israel",
	"IT" => "Italy",
	"JM" => "Jamaica",
	"JP" => "Japan",
	"JE" => "Jersey",
	"JO" => "Jordan",
	"KZ" => "Kazakhstan",
	"KE" => "Kenya",
	"KI" => "Kiribati",
	"KP" => "Korea (North)",
	"KR" => "Korea (South)",
	"XK" => "Kosovo",
	"KW" => "Kuwait",
	"KG" => "Kyrgyzstan",
	"LA" => "Laos",
	"LV" => "Latvia",
	"LB" => "Lebanon",
	"LS" => "Lesotho",
	"LR" => "Liberia",
	"LY" => "Libyan Arab Jamahiriya",
	"LI" => "Liechtenstein",
	"LT" => "Lithuania",
	"LU" => "Luxembourg",
	"MO" => "Macao",
	"MK" => "Macedonia",
	"MG" => "Madagascar",
	"MW" => "Malawi",
	"MY" => "Malaysia",
	"MV" => "Maldives",
	"ML" => "Mali",
	"MT" => "Malta",
	"MH" => "Marshall Islands",
	"MQ" => "Martinique",
	"MR" => "Mauritania",
	"MU" => "Mauritius",
	"YT" => "Mayotte",
	"MX" => "Mexico",
	"FM" => "Micronesia",
	"MD" => "Moldova",
	"MC" => "Monaco",
	"MN" => "Mongolia",
	"MS" => "Montserrat",
	"MA" => "Morocco",
	"MZ" => "Mozambique",
	"MM" => "Myanmar",
	"NA" => "Namibia",
	"NR" => "Nauru",
	"NP" => "Nepal",
	"NL" => "Netherlands",
	"AN" => "Netherlands Antilles",
	"NC" => "New Caledonia",
	"NZ" => "New Zealand",
	"NI" => "Nicaragua",
	"NE" => "Niger",
	"NG" => "Nigeria",
	"NU" => "Niue",
	"NF" => "Norfolk Island",
	"MP" => "Northern Mariana Islands",
	"NO" => "Norway",
	"OM" => "Oman",
	"PK" => "Pakistan",
	"PW" => "Palau",
	"PS" => "Palestinian Territory, Occupied",
	"PA" => "Panama",
	"PG" => "Papua New Guinea",
	"PY" => "Paraguay",
	"PE" => "Peru",
	"PH" => "Philippines",
	"PN" => "Pitcairn",
	"PL" => "Poland",
	"PT" => "Portugal",
	"PR" => "Puerto Rico",
	"QA" => "Qatar",
	"RE" => "Reunion",
	"RO" => "Romania",
	"RU" => "Russian Federation",
	"RW" => "Rwanda",
	"SH" => "Saint Helena",
	"KN" => "Saint Kitts and Nevis",
	"LC" => "Saint Lucia",
	"PM" => "Saint Pierre and Miquelon",
	"VC" => "Saint Vincent and the Grenadines",
	"WS" => "Samoa",
	"SM" => "San Marino",
	"ST" => "Sao Tome and Principe",
	"SA" => "Saudi Arabia",
	"SN" => "Senegal",
	"RS" => "Serbia",
	"ME" => "Montenegro",
	"SC" => "Seychelles",
	"SL" => "Sierra Leone",
	"SG" => "Singapore",
	"SK" => "Slovakia",
	"SI" => "Slovenia",
	"SB" => "Solomon Islands",
	"SO" => "Somalia",
	"ZA" => "South Africa",
	"GS" => "South Georgia and the South Sandwich Islands",
	"ES" => "Spain",
	"LK" => "Sri Lanka",
	"SD" => "Sudan",
	"SR" => "Suriname",
	"SJ" => "Svalbard and Jan Mayen",
	"SZ" => "Swaziland",
	"SE" => "Sweden",
	"CH" => "Switzerland",
	"SY" => "Syrian Arab Republic",
	"TW" => "Taiwan, Province of China",
	"TJ" => "Tajikistan",
	"TZ" => "Tanzania",
	"TH" => "Thailand",
	"TL" => "Timor-Leste",
	"TG" => "Togo",
	"TK" => "Tokelau",
	"TO" => "Tonga",
	"TT" => "Trinidad and Tobago",
	"TN" => "Tunisia",
	"TR" => "Turkey",
	"TM" => "Turkmenistan",
	"TC" => "Turks and Caicos Islands",
	"TV" => "Tuvalu",
	"UG" => "Uganda",
	"UA" => "Ukraine",
	"AE" => "United Arab Emirates",
	"GB" => "United Kingdom",
	"US" => "United States",
	"UM" => "United States Minor Outlying Islands",
	"UY" => "Uruguay",
	"UZ" => "Uzbekistan",
	"VU" => "Vanuatu",
	"VE" => "Venezuela",
	"VN" => "Viet Nam",
	"VG" => "Virgin Islands, British",
	"VI" => "Virgin Islands, U.S.",
	"WF" => "Wallis and Futuna",
	"EH" => "Western Sahara",
	"YE" => "Yemen",
	"ZM" => "Zambia",
	"ZW" => "Zimbabwe",
);

$MBLIMITS = array(
	"1024" => '1 MB',
	"2048" => '2 MB',
	"3072" => '3 MB',
	"4096" => '4 MB',
	"5120" => '5 MB',
	"10240" => '10 MB',
	"15360" => '15 MB',
	"20480" => '20 MB',
	"25600" => '25 MB',
	"30720" => '30 MB',
	"40960" => '40 MB',
	"51200" => '50 MB',
	"102400" => '100 MB',
	"153600" => '150 MB',
	"256000" => '250 MB',
	"307200" => '300 MB',
	"512000" => '500 MB',
	"716800" => '700 MB',
	"819200" => '800 MB',
	"1024000" => '1 GB',
	"2048000" => '2 GB',
	"3072000" => '3 GB',
	"5120000" => '5 GB',
);

$LIMITLENGTH = array("100", "150", "200", "250", "300", "350", "400", "450", "500");
$POSTLIMIT = array("5", "10", "15", "20", "25", "30", "35", "40", "45");
$PAGINATIONLIMIT = array("10", "20", "30", "40", "50", "60", "70", "80", "90", "100");
$LIVETIMELIMIT = array("10", "20", "30", "40", "50", "60", "70", "80", "90", "100");

$S3REGIONS = array(
	"us-east-1" => "US East (N. Virginia)",
	"us-east-2" => "US East (Ohio)",
	"us-west-1" => "US West (N. California)",
	"us-west-2" => "US West (Oregon)",
	"ap-northeast-2" => "Asia Pacific (Seoul)",
	"ap-south-1" => "Asia Pacific (Mumbai)",
	"ap-southeast-1" => "Asia Pacific (Singapore)",
	"ap-southeast-2" => "Asia Pacific (Sydney)",
	"ap-northeast-1" => "Asia Pacific (Tokyo)",
	"ca-central-1" => "Canada (Central)",
	"eu-central-1" => "EU (Frankfurt)",
	"eu-west-1" => "EU (Ireland)",
	"eu-west-2" => "EU (London)",
	"sa-east-1" => "South America (São Paulo)",
);

class TimeAgo {
	/** Seconds in minute
	 * @var	Integer
	 */
	private static $m = 60;

	/** Seconds in hour
	 * @var	Integer
	 */
	private static $h = 3600;

	/** Seconds in day
	 * @var	Integer
	 */
	private static $d = 86400;

	/** Seconds in week
	 * @var	Integer
	 */
	private static $w = 604800;

	/** Seconds in mounth
	 * @var	Integer
	 */
	private static $mo = 2629800;

	/** Seconds in year
	 * @var	Integer
	 */
	private static $y = 31557600;

	/** Tamplates for language expressions stored in array
	 * @var Array
	 */
	public static $string = array(
		"now" => "now",
		"second" => "a second ago",
		"seconds" => "%d seconds ago",
		"minute" => "a minute ago",
		"minutes" => "%d minutes ago",
		"hour" => "about an hour ago",
		"hours" => "%d hours ago",
		"yesterday" => "yesterday",
		"days" => "%d days ago",
		"on" => "on %s",
		"week" => "week ago",
		"weeks" => "%d weeks ago",
		"month" => "a month ago",
		"months" => "%d months ago",
		"year" => "a year ago",
		"years" => "%d years ago",
	);

	/** String days of week stored in array (0 is Sunday, 6 is Saturday)
	 *  @var Array
	 */
	public static $weekDays = array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday");

	/** Function to calcuate elapsed time (Check link for valid formats)
	 * @param 	String 	$time			- Time
	 * @param 	String 	$calculateFrom 	- Start time difference calculation from
	 * @return 	String 	- Language expression of time difference
	 * @link	http://www.php.net/manual/en/datetime.formats.php
	 */
	public static function ago($time, $calculateFrom = 'now') {

		// Calculate to
		$t = strtotime($time);
		// Calculate from
		$c = strtotime($calculateFrom);
		// Elapsed
		$e = $c - $t;
		// Elapsed that day
		$de = date("H", $c) * TimeAgo::$h + date("i", $c) * TimeAgo::$m + date("s", $c);

		if ($e < TimeAgo::$m) {
			// Now / Second / Seconds
			return ($e == 0) ? TimeAgo::$string['now'] : ($e == 1 ? TimeAgo::$string['second'] : sprintf(TimeAgo::$string['seconds'], $e));
		} elseif ($e < TimeAgo::$h) {
			// Minutes
			return (($m = intval($e / TimeAgo::$m)) && $m == 1) ? TimeAgo::$string['minute'] : sprintf(TimeAgo::$string['minutes'], $m);
		} elseif ($e < TimeAgo::$d) {
			// Today - Hours
			return (($h = intval($e / TimeAgo::$h)) && $h == 1) ? TimeAgo::$string['hour'] : sprintf(TimeAgo::$string['hours'], $h);
		} elseif ($e <= TimeAgo::$d + $de) {
			// Yesterday
			return TimeAgo::$string['yesterday'];
		} elseif ($e < TimeAgo::$d * 6 + $de) {
			// Last week
			return sprintf(TimeAgo::$string['on'], TimeAgo::$weekDays[date("w", $t)]);
		} elseif ($e < TimeAgo::$mo) {
			// less then month
			// Weeks
			if ($e < TimeAgo::$w * 2) {
				// Last seven days
				return TimeAgo::$string['week'];
			} elseif ($e < TimeAgo::$w * 3) {
				// 2 weeks
				return sprintf(TimeAgo::$string['weeks'], 2);
			} else {
				// 3 weeks
				return sprintf(TimeAgo::$string['weeks'], 3);
			}
		} elseif ($e < TimeAgo::$y) {
			// less then year
			// Month / Months
			return ($e < TimeAgo::$mo * 2) ? TimeAgo::$string['month'] : sprintf(TimeAgo::$string['months'], intval($e / TimeAgo::$mo));
		} else {
			// Year / Years
			return ($e >= TimeAgo::$y && $e < TimeAgo::$y * 2) ? TimeAgo::$string['year'] : sprintf(TimeAgo::$string['years'], intval($e / TimeAgo::$y));
		}
	}
}
?>